
services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:tallent_password@db:5432/mydatabase"
    env_file:
      - .env
    command: >
      sh -c "node dist/index.js"

  db:
    image: postgres
    container_name: tallent_container
    environment:
      POSTGRES_PASSWORD: tallent_password
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" 
    volumes:
      - tallent_volume:/var/lib/postgresql/data
      - tallent_user_storage:/app/uploads

volumes:
  tallent_volume:
  tallent_user_storage: